version: "3.7"


services:
  mock_server:
    build: ./tests/server
    command: python server.py
    ports:
    - 8080:8080
    networks:
      clientator:
        aliases:
          - mock_server

networks:
  clientator:
    driver: bridge
